aaa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from .views import home

urlpatterns = [
    path('', home, name='home'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('apps/', include('apps.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path

from .views import (
    index,
    signup,
    login,
    logout,
    profile,
)

app_name = 'accounts'

urlpatterns = [
    path('', index, name='index'),
    path('signup/', signup, name='signup'),
    path('login/', login, name='login'),
    path('logout/', logout, name='logout'),
    path('profile/', profile, name='profile'),
]

apps/urls.py
from django.urls import path

from .views import (
    index, 
    create,
    detail,
    delete,
    update,
)

app_name = 'apps'

urlpatterns = [
    path('', index, name='index'),
    path('create/', create, name='create'),
    path('<int:pk>/detail/', detail, name='detail'),
    path('<int:pk>/delete/', delete, name='delete'),
    path('<int:pk>/update/', update, name='update'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class CustomUser(AbstractUser):
    pass

apps/models.py
from django.db import models

# Create your models here.
class App(models.Model):
    number = models.IntegerField()
    title = models.CharField(max_length=200)
    overview = models.TextField()
    image = models.ImageField(upload_to='apps', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm
from django.contrib.auth import get_user_model

CustomUser = get_user_model()

class CustomUserChangeForm(UserChangeForm):
    # class Meta(UserChangeForm.Meta):
    class Meta:
        model = CustomUser
        fields = ['username', 'first_name', 'last_name']

class CustomUserCreationForm(UserCreationForm):
    # class Meta(UserCreationForm.Meta):
    class Meta:
        model = CustomUser
        fields = UserCreationForm.Meta.fields

apps/forms.py
from django.forms import ModelForm

from .models import App

class AppForm(ModelForm):
    class Meta():
        model = App
        fields = '__all__'

aaa/views.py
from django.shortcuts import render, redirect

def home(request):
    return render(request, 'home.html')

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required

from .forms import CustomUserChangeForm, CustomUserCreationForm

# Create your views here.
def index(request):
    return render(request, 'accounts/index.html')

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('home')
    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/form.html', context)


def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('home')
    else:
        form = AuthenticationForm()
    context = {
        'form': form,
    }
    return render(request, 'accounts/form.html', context)

def logout(request):
    if request.user.is_authenticated:
        auth_logout(request)
    return redirect('home')

@login_required
def profile(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form': form,
    }
    return render(request, 'accounts/form.html', context)

        
        

apps/views.py
from django.shortcuts import render, redirect, get_object_or_404

from .forms import AppForm
from .models import App

# Create your views here.
def index(request):
    apps = App.objects.all()
    context = {
        'apps': apps,
    }
    return render(request, 'apps/index.html', context)

def create(request):
    if request.method == 'POST':
        form = AppForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('apps:index')
    else:
        form = AppForm()
    context = {
        'form': form,
    }
    return render(request, 'apps/create.html', context)

def detail(request, *args, **kwargs):
    app = get_object_or_404(App, pk=kwargs.get('pk'))
    context = {
        'app': app,
    }
    return render(request, f'apps/{app.number}/index.html', context)

def delete(request, *args, **kwargs):
    app = get_object_or_404(App, pk=kwargs.get('pk'))
    app.delete()
    return redirect('apps:index')

def update(request, *args, **kwargs):
    app = get_object_or_404(App, pk=kwargs.get('pk'))
    if request.method == 'POST':
        form = AppForm(request.POST, request.FILES, instance=app)
        if form.is_valid():
            form.save()
            return redirect('apps:index')
    else:
        form = AppForm(instance=app)
    context = {
        'form': form,
    }
    return render(request, 'apps/create.html', context)
    

aaa/templates/apps_list.html
{% extends 'base.html' %}

{% block content %}
<h1>Apps List</h1>
{% endblock %}

aaa/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  {% include 'base/_css.html' %}
  <link rel="stylesheet" href="{% static 'base.css' %}">
  {% block css %}
  {% endblock %}
</head>
<body>
  {% include 'base/_navbar.html' %}
  {% include 'base/_messages.html' %}
  
  {% block content %}
  {% endblock %}

  {% include 'base/_js.html' %}

  {% block js %}
  {% endblock %}
</body>
</html>

aaa/templates/base/_css.html
<!-- Bootstrap -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

aaa/templates/base/_js.html
<!-- Bootstrap -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

aaa/templates/base/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav justify-content-between w-100">
        <!-- left -->
        <div class="d-flex">
          <li class="nav-item">
            <a class="nav-link active fw-bolder" aria-current="page" href="{% url 'home' %}">Javascript 30</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'apps:index' %}">All Apps</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'apps:create' %}">Create New App</a>
          </li>
        </div>
        
        <!-- middle -->
        {% if app %}
        <div class="d-flex text-light align-items-center">
          <p class="m-0">#{{ app.number }}: {{ app.title }}</p>
        </div>
        {% endif %}

        <!-- right -->
        <div class="d-flex">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              {{ user.username }}
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <li><a class="dropdown-item" href="{% url 'accounts:profile' %}">Profile</a></li>
              <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a></li>
            </ul>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:signup' %}">Signup</a>
          </li>
          {% endif %}
        </div>
      </ul>
    </div>
  </div>
</nav>

aaa/templates/home.html
{% extends 'base.html' %}

{% block content %}
<h1>Home</h1>
{% endblock %}

accounts/templates/accounts/form.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="POST">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="submit">
</form>
{% endblock %}

accounts/templates/accounts/index.html
{% extends 'base.html' %}

{% block content %}
<h1>Accounts Home</h1>
{% endblock %}

apps/templates/apps/1/index.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" href="{% static '1/index.css' %}">
{% endblock %}

{% block content %}
<div class="my-container container">
  <div class="row drum-container align-items-center">
    <div class="drum-btn-container col-1 offset-1">
      <div class="drum-btn">
        <p>a</p>
        <h3 class="drum-kind">a</h3>
      </div>
    </div>
    <div class="drum-btn-container col-1">
      <div class="drum-btn">
        <p>s</p>
        <h3 class="drum-kind">s</h3>
      </div>
    </div>
    <div class="drum-btn-container col-1">
      <div class="drum-btn">
        <p>d</p>
        <h3 class="drum-kind">d</h3>
      </div>
    </div>
    <div class="drum-btn-container col-1">
      <div class="drum-btn">
        <p>f</p>
        <h3 class="drum-kind">f</h3>
      </div>
    </div>
    <div class="drum-btn-container col-1">
      <div class="drum-btn">
        <p>g</p>
        <h3 class="drum-kind">g</h3>
      </div>
    </div>
    <div class="drum-btn-container col-1">
      <div class="drum-btn">
        <p>h</p>
        <h3 class="drum-kind">h</h3>
      </div>
    </div>
    <div class="drum-btn-container col-1">
      <div class="drum-btn">
        <p>j</p>
        <h3 class="drum-kind">j</h3>
      </div>
    </div>
    <div class="drum-btn-container col-1">
      <div class="drum-btn">
        <p>k</p>
        <h3 class="drum-kind">k</h3>
      </div>
    </div>
    <div class="drum-btn-container col-1">
      <div class="drum-btn">
        <p>l</p>
        <h3 class="drum-kind">l</h3>
      </div>
    </div>
    <div class="drum-btn-container col-1">
      <div class="drum-btn">
        <p>;</p>
        <h3 class="drum-kind">;</h3>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block js %}
<script>
const drumContainer = document.querySelector(".drum-container");

console.log(drumContainer);

</script>
{% endblock %}

apps/templates/apps/_card.html
<a class="text-decoration-none text-dark"href="{% url 'apps:detail' pk=app.pk %}">
  <div class="card">
    <img src="{{ app.image.url }}" class="card-img-top" alt="{{ app.image }}">
    <div class="card-body">
      <h5 class="card-title">#{{ app.number }} : {{ app.title }}</h5>
      <p class="card-text">{{ app.overview }}</p>
      <a class="btn btn-success" href="{% url 'apps:update' pk=app.pk %}">update</a>
      <a class="btn btn-warning" href="{% url 'apps:delete' pk=app.pk %}">delete</a>
    </div>
  </div>
</a>

apps/templates/apps/create.html
{% extends 'base.html' %}

{% block content %}
<form action="" method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Create new App">
</form>
{% endblock %}

apps/templates/apps/detail.html
{% extends 'base.html' %}

{% block content %}
{% endblock %}

apps/templates/apps/index.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="row">
    {% for app in apps %}
    <div class="col-4">
      {% include 'apps/_card.html' %}
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}